/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param code
 * @param type
 * @param amount
 * @param totalValue
 */


data class Asset(

   @field:JsonProperty("code")
   val code: Asset.Code,

   @field:JsonProperty("type")
   val type: Asset.Type,

   @field:JsonProperty("amount")
   val amount: java.math.BigDecimal,

   @field:JsonProperty("totalValue")
   val totalValue: java.math.BigDecimal,

   ) {

   /**
    *
    *
    * Values: BTC,ETH,APPLE,TESLA,GOLD,SILVER
    */
   enum class Code(val value: kotlin.String) {
      @JsonProperty(value = "BTC")
      BTC("BTC"),

      @JsonProperty(value = "ETH")
      ETH("ETH"),

      @JsonProperty(value = "APPLE")
      APPLE("APPLE"),

      @JsonProperty(value = "TESLA")
      TESLA("TESLA"),

      @JsonProperty(value = "GOLD")
      GOLD("GOLD"),

      @JsonProperty(value = "SILVER")
      SILVER("SILVER");
   }

   /**
    *
    *
    * Values: CRYPTO,STOCK,COMMODITY
    */
   enum class Type(val value: kotlin.String) {
      @JsonProperty(value = "CRYPTO")
      CRYPTO("CRYPTO"),

      @JsonProperty(value = "STOCK")
      STOCK("STOCK"),

      @JsonProperty(value = "COMMODITY")
      COMMODITY("COMMODITY");
   }

}

