/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param sourceAssetCode
 * @param sourceAmount
 * @param targetAssetCode
 * @param targetAmount
 */


data class Conversion(

   @field:JsonProperty("sourceAssetCode")
   val sourceAssetCode: AssetCode,

   @field:JsonProperty("sourceAmount")
   val sourceAmount: java.math.BigDecimal,

   @field:JsonProperty("targetAssetCode")
   val targetAssetCode: AssetCode,

   @field:JsonProperty("targetAmount")
   val targetAmount: java.math.BigDecimal,

   ) {


}

