/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param sourceAssetCode
 * @param sourceAmount
 * @param targetAssetCode
 * @param targetAmount
 */


data class Conversion(

   @field:JsonProperty("sourceAssetCode")
   val sourceAssetCode: Conversion.SourceAssetCode,

   @field:JsonProperty("sourceAmount")
   val sourceAmount: java.math.BigDecimal,

   @field:JsonProperty("targetAssetCode")
   val targetAssetCode: Conversion.TargetAssetCode,

   @field:JsonProperty("targetAmount")
   val targetAmount: java.math.BigDecimal,

   ) {

   /**
    *
    *
    * Values: BTC,ETH,APPLE,TESLA,GOLD,SILVER
    */
   enum class SourceAssetCode(val value: kotlin.String) {
      @JsonProperty(value = "BTC")
      BTC("BTC"),

      @JsonProperty(value = "ETH")
      ETH("ETH"),

      @JsonProperty(value = "APPLE")
      APPLE("APPLE"),

      @JsonProperty(value = "TESLA")
      TESLA("TESLA"),

      @JsonProperty(value = "GOLD")
      GOLD("GOLD"),

      @JsonProperty(value = "SILVER")
      SILVER("SILVER");
   }

   /**
    *
    *
    * Values: BTC,ETH,APPLE,TESLA,GOLD,SILVER
    */
   enum class TargetAssetCode(val value: kotlin.String) {
      @JsonProperty(value = "BTC")
      BTC("BTC"),

      @JsonProperty(value = "ETH")
      ETH("ETH"),

      @JsonProperty(value = "APPLE")
      APPLE("APPLE"),

      @JsonProperty(value = "TESLA")
      TESLA("TESLA"),

      @JsonProperty(value = "GOLD")
      GOLD("GOLD"),

      @JsonProperty(value = "SILVER")
      SILVER("SILVER");
   }

}

