/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param userId
 * @param type
 * @param assetCode
 * @param amount
 * @param unitPrice
 * @param totalPrice
 */


data class Exchange(

   @field:JsonProperty("id")
   val id: kotlin.Int,

   @field:JsonProperty("userId")
   val userId: kotlin.Int,

   @field:JsonProperty("type")
   val type: ExchangeType,

   @field:JsonProperty("assetCode")
   val assetCode: AssetCode,

   @field:JsonProperty("amount")
   val amount: java.math.BigDecimal,

   @field:JsonProperty("unitPrice")
   val unitPrice: java.math.BigDecimal,

   @field:JsonProperty("totalPrice")
   val totalPrice: java.math.BigDecimal,

   ) {


}

