/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param type
 * @param assetCode
 * @param amount
 */


data class ExchangeForm(

   @field:JsonProperty("type")
   val type: ExchangeType,

   @field:JsonProperty("assetCode")
   val assetCode: AssetCode,

   @field:JsonProperty("amount")
   val amount: java.math.BigDecimal,

   ) {


}

