/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param type
 * @param amount
 */


data class TransactionForm(

   @field:JsonProperty("type")
   val type: TransactionForm.Type,

   @field:JsonProperty("amount")
   val amount: java.math.BigDecimal,

   ) {

   /**
    *
    *
    * Values: DEPOSIT,WITHDRAWAL
    */
   enum class Type(val value: kotlin.String) {
      @JsonProperty(value = "DEPOSIT")
      DEPOSIT("DEPOSIT"),

      @JsonProperty(value = "WITHDRAWAL")
      WITHDRAWAL("WITHDRAWAL");
   }

}

