/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
   "ArrayInDataClass",
   "EnumEntryName",
   "RemoveRedundantQualifierName",
   "UnusedImport"
)

package org.openapitools.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param name
 * @param transactions
 * @param exchanges
 * @param balance
 * @param assets
 */


data class User(

   @field:JsonProperty("id")
   val id: kotlin.Int,

   @field:JsonProperty("name")
   val name: kotlin.String,

   @field:JsonProperty("transactions")
   val transactions: kotlin.collections.List<Transaction>,

   @field:JsonProperty("exchanges")
   val exchanges: kotlin.collections.List<Exchange>,

   @field:JsonProperty("balance")
   val balance: java.math.BigDecimal,

   @field:JsonProperty("assets")
   val assets: kotlin.collections.List<Asset>,

   ) {


}

